In [2]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
import statsmodels.formula.api as sf
from statsmodels.formula.api import ols

In [4]:
df = pd.read_excel(r'C:\Users\tyagir01\Desktop\Data Analytics Problem Set\SOM.xlsx')
df.head()

Tenasity  Hardness
0      53.1    239.11
1      70.2    348.63
2      84.3    368.19
3      55.3    301.21
4      78.5    353.97

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
h = df['Hardness']
k = df['Tenasity']

In [7]:
x = df['Hardness'].values.reshape(-1,1)
y = df['Tenasity'].values.reshape(-1,1)
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 213)

In [8]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((28, 1), (7, 1), (28, 1), (7, 1))

In [9]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
reg.intercept_

array([34.7658897])

In [11]:
reg.coef_

array([[0.10713093]])

In [12]:
y_predict = reg.predict(x_test)
y_predict

array([[65.52317868],
       [60.38196552],
       [65.48461154],
       [59.63204903],
       [68.25287468],
       [64.76147779],
       [63.11487545]])

In [13]:
mean_squared_error(y_test, y_predict)

171.73849385169703

In [14]:
reg.score(x_test, y_test)

-0.15003350927155967

In [15]:
reg.score(x_train, y_train)

0.12375233886499049